
import json
from pathlib import Path
from datetime import datetime, timezone

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"

OUTCOMES_FILE = DATA_DIR / "outcomes.jsonl"


# ======================================================================
# RecoverOS - SANDBOX OUTCOME RUNNER
# ======================================================================
#
# This creates OBSERVED SANDBOX outcomes.
#
# IMPORTANT:
# - These are NOT real customer payments.
# - They are NOT production outcomes.
# - They are generated by a deterministic sandbox environment.
# - They must remain separate from genuine production evidence.
#
# ======================================================================


SANDBOX_CASES = [
    {
        "payment_id": "SANDBOX_001",
        "amount": 1800,
        "failure_reason": "bank_timeout",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.82,
        "final_action": "retry_payment",
        "sandbox_result": True,
    },
    {
        "payment_id": "SANDBOX_002",
        "amount": 3200,
        "failure_reason": "bank_timeout",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.79,
        "final_action": "retry_payment",
        "sandbox_result": True,
    },
    {
        "payment_id": "SANDBOX_003",
        "amount": 1500,
        "failure_reason": "insufficient_funds",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.45,
        "final_action": "send_update_link",
        "sandbox_result": False,
    },
    {
        "payment_id": "SANDBOX_004",
        "amount": 4200,
        "failure_reason": "bank_timeout",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.84,
        "final_action": "retry_payment",
        "sandbox_result": True,
    },
    {
        "payment_id": "SANDBOX_005",
        "amount": 2750,
        "failure_reason": "network_error",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.76,
        "final_action": "retry_payment",
        "sandbox_result": True,
    },
    {
        "payment_id": "SANDBOX_006",
        "amount": 2100,
        "failure_reason": "insufficient_funds",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.40,
        "final_action": "send_update_link",
        "sandbox_result": False,
    },
    {
        "payment_id": "SANDBOX_007",
        "amount": 3600,
        "failure_reason": "bank_timeout",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.81,
        "final_action": "retry_payment",
        "sandbox_result": True,
    },
    {
        "payment_id": "SANDBOX_008",
        "amount": 1900,
        "failure_reason": "network_error",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.74,
        "final_action": "retry_payment",
        "sandbox_result": True,
    },
    {
        "payment_id": "SANDBOX_009",
        "amount": 5000,
        "failure_reason": "insufficient_funds",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.38,
        "final_action": "send_update_link",
        "sandbox_result": False,
    },
    {
        "payment_id": "SANDBOX_010",
        "amount": 2500,
        "failure_reason": "bank_timeout",
        "payment_method": "netbanking",
        "merchant_type": "saas",
        "recovery_probability": 0.85,
        "final_action": "retry_payment",
        "sandbox_result": True,
    },
]


def create_observed_outcome(case):
    recovered = bool(case["sandbox_result"])

    recovery_amount = (
        float(case["amount"])
        if recovered
        else 0.0
    )

    expected_revenue = (
        float(case["amount"])
        * float(case["recovery_probability"])
    )

    return {
        "timestamp": datetime.now(
            timezone.utc
        ).isoformat(),

        "payment_id": case["payment_id"],

        "amount": float(
            case["amount"]
        ),

        "failure_reason": case[
            "failure_reason"
        ],

        "payment_method": case[
            "payment_method"
        ],

        "merchant_type": case[
            "merchant_type"
        ],

        "recommended_action": case[
            "final_action"
        ],

        "final_action": case[
            "final_action"
        ],

        "recovery_probability": float(
            case["recovery_probability"]
        ),

        "expected_revenue": expected_revenue,

        "recovered": recovered,

        "recovery_amount": recovery_amount,

        # Explicit provenance.
        "data_source": "SANDBOX",

        # Never claim this is production.
        "production": False,

        # The outcome was observed from the sandbox result.
        "outcome_observed": True,
    }


def save_outcome(record):

    DATA_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        OUTCOMES_FILE,
        "a",
        encoding="utf-8"
    ) as file:

        file.write(
            json.dumps(record)
            + "\n"
        )


def main():

    print("=" * 70)
    print("RecoverOS - SANDBOX OUTCOME RUNNER")
    print("=" * 70)

    print()
    print("MODE")
    print("-" * 70)
    print("SANDBOX")
    print("These are observed sandbox outcomes.")
    print("They are NOT real customer production outcomes.")
    print()

    created = 0

    for case in SANDBOX_CASES:

        record = create_observed_outcome(
            case
        )

        save_outcome(
            record
        )

        created += 1

        print(
            f"{record['payment_id']:14}"
            f" Recovered={str(record['recovered']):5}"
            f" Amount=₹{record['amount']:.2f}"
            f" Action={record['final_action']}"
        )

    print()
    print("=" * 70)
    print("SANDBOX RUN COMPLETED")
    print("=" * 70)

    print(
        f"Outcomes created : {created}"
    )

    print(
        f"Saved to         : {OUTCOMES_FILE}"
    )

    print()
    print(
        "Production flag : FALSE"
    )

    print(
        "Data source     : SANDBOX"
    )

    print()
    print(
        "These records must not be presented"
    )

    print(
        "as real production customer outcomes."
    )

    print("=" * 70)


if __name__ == "__main__":
    main()

